"""Flow 3: quick course + quiz.

All the content (lesson, questions, options, correct answer) is generated by
Claude; interpreting the user's quiz answers is also delegated to Claude
(`interpret_quiz_answer`) — no text matching of our own.

Note: the reply strings below are intentionally left in Spanish — see the
note at the top of flows/onboarding.py for why.
"""

from __future__ import annotations

from typing import Any

from shared.message import NormalizedMessage
from shared.mqtt_client import ManagedMqttConnection
from shared.postgrest_client import PostgrestClient

from ..claude_client import generate_course, interpret_quiz_answer
from ..conversation import clear_keys, update_state
from ..messaging import reply

# This flow's own state keys inside conversation.state.
_STATE_KEYS = ("pending_action", "course_topic", "quiz_questions", "quiz_index", "quiz_correct")


def _format_question(question: dict[str, Any], index: int, total: int) -> str:
    options = "\n".join(f"{chr(65 + i)}) {opt}" for i, opt in enumerate(question["options"]))
    return f"Pregunta {index + 1}/{total}: {question['question']}\n{options}"


async def start_course(
    pg: PostgrestClient,
    mqtt: ManagedMqttConnection,
    conversation: dict[str, Any],
    msg: NormalizedMessage,
    topic: str,
) -> None:
    course = await generate_course(topic)
    # From here on we work with plain dicts (JSON-serializable) — that's what
    # they'll turn into anyway after the first roundtrip through PostgREST.
    questions = [q.model_dump() for q in course.questions]

    new_state = {
        **conversation["state"],
        "pending_action": "course_quiz",
        "course_topic": topic,
        "quiz_questions": questions,
        "quiz_index": 0,
        "quiz_correct": 0,
    }
    await update_state(pg, conversation["id"], new_state)

    await reply(mqtt, msg, course.lesson)
    await reply(mqtt, msg, _format_question(questions[0], 0, len(questions)))


async def handle_quiz_answer(
    pg: PostgrestClient,
    mqtt: ManagedMqttConnection,
    conversation: dict[str, Any],
    msg: NormalizedMessage,
) -> None:
    state = conversation["state"]
    questions: list[dict[str, Any]] = state["quiz_questions"]
    index: int = state["quiz_index"]
    question = questions[index]

    selected = await interpret_quiz_answer(question["question"], question["options"], msg.content or "")
    if selected is None:
        await reply(mqtt, msg, "No he entendido tu respuesta — indica la opción (ej. 'la B' o el texto de la opción).")
        return

    correct = selected == question["correct_index"]
    correct_count = state["quiz_correct"] + (1 if correct else 0)
    feedback = "¡Correcto!" if correct else f"No exactamente — la respuesta correcta era: {question['options'][question['correct_index']]}"

    next_index = index + 1
    if next_index >= len(questions):
        final_state = clear_keys(state, *_STATE_KEYS)
        await update_state(pg, conversation["id"], final_state)
        await reply(mqtt, msg, f"{feedback}\n\nTest completado: {correct_count}/{len(questions)} correctas.")
        return

    new_state = {**state, "quiz_index": next_index, "quiz_correct": correct_count}
    await update_state(pg, conversation["id"], new_state)
    await reply(mqtt, msg, feedback)
    await reply(mqtt, msg, _format_question(questions[next_index], next_index, len(questions)))
